In [ ]:
## Load in NumPy (have pip installed NumPy first)

In [4]:
import numpy as np

In [ ]:
## The Basics

In [25]:
a = np.array([1,2,3], dtype = 'int64')
print(a)

[1 2 3]


In [19]:
b = np.array([[9.2, 26.45, 4.2, 13.5, 4.2], [4,2,3,4,6]])
print(b)

[[ 9.2  26.45  4.2  13.5   4.2 ]
 [ 4.    2.    3.    4.    6.  ]]


In [20]:
b.ndim

2

In [21]:
#getshape
b.shape

(2, 5)

In [26]:
# Get Type 
a.dtype

dtype('int64')

In [32]:
# Get total size (total number of elements)
b.size


10

In [31]:
# Get total bytes (implied memory storage)
a.nbytes

24

In [35]:
## Now we move to change specific columns and so forth

a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [34]:
a.shape

(2, 7)

In [36]:
# Get specific element [row, column]

a[1, 5] # row two, column 6 (remember python uses 0 indexing)

13

In [37]:
# Let's get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
# now a specific column
a[:, 5]

array([ 6, 13])

In [40]:
# Getting more fancy [startindex: endindex: stepsize]
a[0, 1:6:2]



array([2, 4, 6])

In [41]:
a[0, 1:-1:2]

array([2, 4, 6])

In [42]:
# Now we can change individual cells within the specified array

a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [43]:
# See how the second row, 6th column has been changed from 13 to 20....

In [44]:
# Can be applied to a broader set of rows

a[1, :] = 5
a

array([[1, 2, 3, 4, 5, 6, 7],
       [5, 5, 5, 5, 5, 5, 5]])

In [45]:
#Or columns

a[:, 2] = 3
a

array([[1, 2, 3, 4, 5, 6, 7],
       [5, 5, 3, 5, 5, 5, 5]])

In [48]:
b = np.array([[[1,2], [3,4], [5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [49]:
# return specific element - the second duo 
b[:, 1, :]

array([[3, 4]])

In [51]:
# Can directly edit some arrays directly using this method - saves on actual work.

b[:, 1, :] = [[9, 8]]
b

array([[[1, 2],
        [9, 8],
        [5, 6],
        [7, 8]]])

In [57]:
# Lets change the type of arrays we are initialising

np.zeros(5) # Gives a vector of 5



array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((2, 3)) # Gives a structure of 2 by 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.zeros((3,2,3,7)) # Getting more complex here

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]]])

In [63]:
np.ones((3,2,4)) # Can be one with ones for the other set

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [65]:
np.full((2,2), 99) # Specifies a complete array all of the same number - 2 args [size, number]

array([[99, 99],
       [99, 99]])

In [66]:
# Any other number (full_like) - cann take an already built shape (in this case "a"), then specify a number
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [71]:
# Random decimal numbers can be tailored to a specific shape. (doesn't need a tuple to specify if confused)
np.random.rand(4, 5, 2)

array([[[0.29124049, 0.73718201],
        [0.88407548, 0.6395621 ],
        [0.82620389, 0.64752891],
        [0.27694387, 0.326712  ],
        [0.14925166, 0.11774352]],

       [[0.97745394, 0.70105514],
        [0.20706069, 0.10776755],
        [0.90981096, 0.07586445],
        [0.46592132, 0.60775631],
        [0.24247015, 0.34113775]],

       [[0.47157732, 0.38081312],
        [0.23284571, 0.43728966],
        [0.69183894, 0.49804372],
        [0.2722164 , 0.66661027],
        [0.41631774, 0.66925277]],

       [[0.16997266, 0.33643231],
        [0.80574793, 0.96490473],
        [0.00170605, 0.04461948],
        [0.70944575, 0.44526173],
        [0.02430999, 0.68763825]]])

In [76]:
# Random integer values - need to specify the exact size or else it's going to return a 1x1 array (a single number) 
np.random.randint(6, size = (3,4))

array([[5, 2, 0, 0],
       [3, 5, 5, 0],
       [3, 3, 3, 2]])

In [77]:
# Identity matrix - no sizing beyond dimentionality needed as the identity matrix is a square 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [79]:
arr = np.array([[1,2,3]]) # remember the extra square bracket if you want to size it properly
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [86]:
k = np.zeros([5,5])
k[0,:] = 1
k[:,4] = 1
k[4,:] = 1
k[:,0] = 1

k[2,2] = 9
k

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
# This is the more elegant/universal answer - gives some interesting work.

answer = np.ones([5,5])
print(answer)
z = np.zeros([3,3])
z[1,1] = 9
print(z)

answer[1:4,1:4] = z
print(answer)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [98]:
# It's tricky when we make copies of these series

a = np.array([1,3,6,7])
b = a
b[0] = 100
print(b)
print(a) # see how a has changed as well - dont' want that!

[100   3   6   7]
[100   3   6   7]


In [101]:
c = np.array([78,12, 45,90])
d = c.copy()
d[0] = 528
print(d)
print(c) # see how this method is better for making copies.

[528  12  45  90]
[78 12 45 90]


In [103]:
# The maths capabilities in numpy are pretty strong - DMAS is *universal across elements*

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [104]:
a + 2

array([3, 4, 5, 6])

In [105]:
b = np.array([1,5,8,7])

a+b

array([ 2,  7, 11, 11])

In [106]:
b ** 2

array([ 1, 25, 64, 49], dtype=int32)

In [109]:
#Cool trig stuff too!

np.sin(a)
np.cos(a)
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [ ]:
# Linear Algrabra stuff now

In [114]:
a = np.full([2,3],1)
print(a)

b = np.full([3,2],2)
print(b)


 # Can't multiply directly so numpy has a matrix multipication function we can use...
k = np.matmul(a,b)
k

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [115]:
c = np.identity(3)
np.linalg.det(c) # determinant of an identity matrix is always 1

1.0

In [ ]:
# Can do stats stuff too!

In [116]:
stats = np.array([[1,2,3], [4,5,6]])
np.max(stats)

6

In [117]:
np.min(stats)

1

In [122]:
np.min(stats, axis = 1)

array([1, 4])

In [124]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [ ]:
# Reorganising arrays

In [130]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before.shape)

after = before.reshape((8,1))
print(after)

after2 = before.reshape((2,4))
print(after2)

(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]


In [132]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack([h1,h2])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
## Load data from file into python using numpy - have the file in the folder all sorted out

In [137]:
np.genfromtxt('data.txt', delimiter = ",") # set to a float type 

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [140]:
filedata  =np.genfromtxt('data.txt', delimiter = ",")
filedata = filedata.astype('int32') # needs to be done to physically rearrange the data in this way
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
# Advanced indexing (Boolean Masking)

In [141]:
filedata > 50 # Can get false/true outputs for these

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [142]:
filedata[filedata > 50] # Grabs only the values that are greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [143]:
## You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

# Passed in a list and then it indexes in that result 

array([2, 3, 9])

In [144]:
np.any(filedata > 50, axis = 0) # what columns have a value greater than 50? 

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [145]:
np.all(filedata > 50, axis = 0) # what columns have all values greater than 50?

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [147]:
((filedata > 50) & (filedata < 100)) # All the values that are greater than 50, but less than 100

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])